[mypy]
python_version = 3.11
strict = True
# or, if strict is too much at first, use these instead:
# disallow_untyped_defs = True
# check_untyped_defs = True
# warn_unused_ignores = True
# warn_return_any = True

# Only check your actual source, not venv:
mypy_path = backend/src
